# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'nTrust' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
#pod 'FBSDKCoreKit'
#pod 'FBSDKLoginKit'
#pod 'FBSDKShareKit'	
    pod 'FBSDKCoreKit',  '~> 4.42.0'
    pod 'FBSDKLoginKit',  '~> 4.42.0'
    pod 'FBSDKShareKit' , '~> 4.42.0'
  # Pods for nTrust

  target 'nTrust-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'nTrustTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'nTrust-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for nTrust-tvOS

  
end
